version: '3'

services:
  elasticsearch:
    image: elasticsearch:6.4.0
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"

  kibana:
    image: kibana:6.4.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200/
    depends_on:
      - elasticsearch
